import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createTheme, ThemeProvider } from "flowbite-react";
import FacebookIcon from "./components/atoms/icons/lucide/facebook/page";
import InstagramIcon from "./components/atoms/icons/lucide/instagram/page";
import YoutubeIcon from "./components/atoms/icons/lucide/youtube/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const customTheme = createTheme({
  button: {
    color: {
      primary:
        "bg-primary hover:bg-primary-600 focus:ring-primary-300 text-white dark:bg-primary dark:hover:bg-primary-600",
      secondary:
        "bg-secondary hover:bg-secondary-600 focus:ring-secondary-300 text-white dark:bg-secondary dark:hover:bg-secondary-600",
      tertiary:
        "bg-tertiary hover:bg-tertiary-600 focus:ring-tertiary-300 text-white dark:bg-tertiary dark:hover:bg-tertiary-600",
      gray: "bg-neutral-700 hover:bg-neutral-800 focus:ring-neutral-300 text-white dark:bg-neutral-600 dark:hover:bg-neutral-700",
      dark: "bg-neutral-800 hover:bg-neutral-900 focus:ring-neutral-300 text-white dark:bg-neutral-900 dark:hover:bg-neutral-950",
      light:
        "bg-neutral-200 hover:bg-neutral-300 focus:ring-neutral-400 text-neutral-900 dark:bg-neutral-700 dark:hover:bg-neutral-600 dark:text-white",
      success:
        "bg-primary hover:bg-primary-600 focus:ring-primary-300 text-white dark:bg-primary dark:hover:bg-primary-600",
      failure:
        "bg-red-600 hover:bg-red-700 focus:ring-red-300 text-white dark:bg-red-700 dark:hover:bg-red-800",
      warning:
        "bg-yellow-400 hover:bg-yellow-500 focus:ring-yellow-300 text-white dark:bg-yellow-500 dark:hover:bg-yellow-600",
      info: "bg-secondary hover:bg-secondary-600 focus:ring-secondary-300 text-white dark:bg-secondary dark:hover:bg-secondary-600",
      danger:
        "bg-red-600 hover:bg-red-700 focus:ring-red-300 text-white dark:bg-red-700 dark:hover:bg-red-800",
      ghost:
        "bg-transparent hover:bg-neutral-100 focus:ring-neutral-200 text-neutral-900 dark:hover:bg-neutral-800 dark:text-neutral-100",
      alternative:
        "bg-white hover:bg-neutral-100 focus:ring-neutral-200 text-neutral-900 border border-neutral-300 dark:bg-neutral-800 dark:hover:bg-neutral-700 dark:text-neutral-100 dark:border-neutral-600",
      default:
        "bg-primary hover:bg-primary-600 focus:ring-primary-300 text-white dark:bg-primary dark:hover:bg-primary-600",
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col bg-slate-600">
          <main className="flex-1 flex items-center justify-center">
            <ThemeProvider theme={customTheme}>{children}</ThemeProvider>
          </main>
          <footer className="text-center text-sm text-gray-300 py-4 bg-black">
            © 2025 - Todos os direitos reservados.
            <div className="flex justify-center items-center gap-2">
              <FacebookIcon />
              <InstagramIcon />
              <YoutubeIcon />
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
