/* eslint-disable @next/next/no-img-element */
/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" x-data="{ open2faInfo:false, openDevices:false }">
      {/* <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Information - FinTech App</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        slate: {
                            50: '#f8fafc',
                            100: '#f1f5f9',
                            200: '#e2e8f0',
                            300: '#cbd5e1',
                            400: '#94a3b8',
                            500: '#64748b',
                            600: '#475569',
                            700: '#334155',
                            800: '#1e293b',
                            900: '#0f172a'
                        },
                        sky: {
                            400: '#38bdf8',
                            500: '#0ea5e9',
                            600: '#0284c7'
                        },
                        purple: {
                            400: '#a78bfa',
                            500: '#8b5cf6',
                            600: '#7c3aed'
                        }
                    },
                    animation: {
                        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                        'bounce-slow': 'bounce 2s infinite',
                        'fade-in': 'fadeIn 0.5s ease-in-out',
                        'slide-up': 'slideUp 0.6s ease-out'
                    },
                    keyframes: {
                        fadeIn: {
                            '0%': { opacity: '0', transform: 'translateY(10px)' },
                            '100%': { opacity: '1', transform: 'translateY(0)' }
                        },
                        slideUp: {
                            '0%': { opacity: '0', transform: 'translateY(20px)' },
                            '100%': { opacity: '1', transform: 'translateY(0)' }
                        }
                    }
                }
            }
        }
    </script>
    <style>
        .gradient-bg {
            background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 50%, #e2e8f0 100%);
        }
        .card-hover {
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }
        .card-hover:hover {
            transform: translateY(-4px);
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 10px 10px -5px rgba(0, 0, 0, 0.03);
        }
        .security-shield {
            background: linear-gradient(135deg, #0ea5e9 0%, #8b5cf6 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        @media (prefers-reduced-motion: reduce) {
            .card-hover, .animate-slide-up, .animate-fade-in, .animate-pulse-slow {
                animation: none !important;
                transition: none !important;
            }
        }
    </style>
</head> */}
      <body className="gradient-bg min-h-screen text-slate-800">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:bg-white focus:text-slate-800 focus:px-3 focus:py-2 focus:rounded-md focus:ring-2 focus:ring-sky-500"
        >
          Skip to content
        </a>

        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 opacity-10"
        >
          <div
            className="absolute inset-0"
            // style="background-image: url('https://images.unsplash.com/photo-1724204401208-6349fc373543?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MDcxMzN8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMGN5YmVyJTIwc2VjdXJpdHklMjBuZXR3b3JrJTIwYmx1ZSUyMGJhY2tncm91bmQlMjBtaW5pbWFsfGVufDB8MHx8fDE3NTg5Njk2OTR8MA&ixlib=rb-4.1.0&q=80&w=1600'); background-size: cover; background-position: center;"
          ></div>
        </div>

        <main id="main" className="relative max-w-6xl mx-auto px-4 py-8">
          <header className="mb-12 text-center animate-fade-in" role="banner">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-white rounded-full shadow-lg mb-4 ring-1 ring-slate-200/70">
              <i
                className="fas fa-shield-alt text-2xl security-shield"
                aria-hidden="true"
              ></i>
              <span className="sr-only">Security Center</span>
            </div>
            <h1 className="text-4xl font-bold text-slate-900 tracking-tight mb-3">
              Security Center
            </h1>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Advanced protection for your financial data and transactions with
              enterprise-grade security
            </p>

            <div className="hidden md:flex justify-center mt-6">
              <img
                src="https://images.unsplash.com/photo-1680055196833-c2965de0caec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MDcxMzN8MHwxfHNlYXJjaHwxfHxzaGllbGQlMjBpY29uJTIwM2QlMjByZW5kZXIlMjBtaW5pbWFsJTIwYmx1ZSUyMHB1cnBsZXxlbnwwfDB8fHwxNzU4OTY5Njk3fDA&ixlib=rb-4.1.0&q=80&w=640"
                alt="3D shield illustration"
                className="w-40 h-40 object-cover rounded-2xl shadow-md ring-1 ring-slate-200/70"
              />
            </div>
          </header>

          <section
            className="bg-white rounded-2xl shadow-lg border border-slate-200/60 p-8 mb-10 card-hover animate-slide-up"
            aria-labelledby="security-status"
          >
            <div className="flex flex-col md:flex-row items-center justify-between gap-4 mb-6">
              <div className="flex items-center">
                <div
                  className="w-12 h-12 rounded-full flex items-center justify-center mr-4 text-white"
                  aria-hidden="true"
                >
                  <i className="fas fa-check text-lg"></i>
                </div>
                <div>
                  <h2
                    id="security-status"
                    className="text-2xl font-bold text-slate-900"
                  >
                    Security Status
                  </h2>
                  <p className="text-slate-500">Last updated: Just now</p>
                </div>
              </div>
              <span
                className="inline-flex items-center bg-emerald-500 text-white px-4 py-2 rounded-full text-sm font-semibold shadow-lg animate-pulse-slow"
                aria-live="polite"
              >
                <i className="fas fa-shield-check mr-2" aria-hidden="true"></i>
                All Systems Secure
              </span>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              <div className="text-center p-6 bg-slate-50 rounded-xl border border-slate-100 card-hover">
                <div
                  className="w-16 h-16 bg-sky-100 rounded-full flex items-center justify-center mx-auto mb-4 shadow-inner ring-1 ring-sky-200/60"
                  aria-hidden="true"
                >
                  <i className="fas fa-lock text-sky-600 text-2xl"></i>
                </div>
                <h3 className="font-semibold text-slate-900 mb-2 text-lg">
                  Account Protection
                </h3>
                <p className="text-sm text-slate-500 mb-3">
                  Multi-factor authentication enabled
                </p>
                <div
                  className="w-full bg-slate-200 rounded-full h-2"
                  role="progressbar"
                  aria-valuemin={0}
                  aria-valuemax={100}
                  aria-valuenow={95}
                >
                  <div className="bg-green-500 h-2 rounded-full w-[95%]"></div>
                </div>
              </div>

              <div className="text-center p-6 bg-slate-50 rounded-xl border border-slate-100 card-hover">
                <div
                  className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4 shadow-inner ring-1 ring-purple-200/60"
                  aria-hidden="true"
                >
                  <i className="fas fa-key text-purple-600 text-2xl"></i>
                </div>
                <h3 className="font-semibold text-slate-900 mb-2 text-lg">
                  Data Encryption
                </h3>
                <p className="text-sm text-slate-500 mb-3">
                  Bank-level 256-bit encryption
                </p>
                <div
                  className="w-full bg-slate-200 rounded-full h-2"
                  role="progressbar"
                  aria-valuemin={0}
                  aria-valuemax={100}
                  aria-valuenow={100}
                >
                  <div className="bg-purple-500 h-2 rounded-full w-full"></div>
                </div>
              </div>

              <div className="text-center p-6 bg-slate-50 rounded-xl border border-slate-100 card-hover">
                <div
                  className="w-16 h-16 bg-sky-100 rounded-full flex items-center justify-center mx-auto mb-4 shadow-inner ring-1 ring-sky-200/60"
                  aria-hidden="true"
                >
                  <i className="fas fa-eye text-sky-600 text-2xl"></i>
                </div>
                <h3 className="font-semibold text-slate-900 mb-2 text-lg">
                  Activity Monitoring
                </h3>
                <p className="text-sm text-slate-500 mb-3">
                  Real-time transaction monitoring
                </p>
                <div
                  className="w-full bg-slate-200 rounded-full h-2"
                  role="progressbar"
                  aria-valuemin={0}
                  aria-valuemax={100}
                  aria-valuenow={90}
                >
                  <div className="bg-blue-500 h-2 rounded-full w-[90%]"></div>
                </div>
              </div>
            </div>
          </section>

          <section className="  grid lg:grid-cols-2 gap-8 mb-10">
            <div className="space-y-6">
              <div
                className="relative overflow-hidden bg-white rounded-2xl shadow-lg border border-slate-200/60 p-6 card-hover animate-slide-up"
                // style="animation-delay: 0.1s"
              >
                <div className="flex items-start mb-4">
                  <div
                    className="w-10 h-10 bg-purple-600 rounded-full flex items-center justify-center mr-4 text-white"
                    aria-hidden="true"
                  >
                    <i className="fas fa-mobile-alt"></i>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-slate-900">
                      Two-Factor Authentication
                    </h3>
                    <p className="text-slate-600 mt-1">
                      Add an extra layer of security to your account
                    </p>
                  </div>
                  <img
                    src="https://images.unsplash.com/photo-1750043158403-6347fd388451?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MDcxMzN8MHwxfHNlYXJjaHwxfHx0d28lMjBmYWN0b3IlMjBhdXRoZW50aWNhdGlvbiUyMHNtYXJ0cGhvbmUlMjBhcHAlMjBpbGx1c3RyYXRpb258ZW58MHwwfHx8MTc1ODk2OTY5NHww&ixlib=rb-4.1.0&q=80&w=480"
                    alt="Two-factor authentication app"
                    className="hidden md:block w-28 h-20 object-cover rounded-lg ml-4 ring-1 ring-slate-200/70"
                  />
                </div>
                <p className="text-slate-600 mb-6">
                  We recommend using an authenticator app for maximum security.
                  Get instant notifications for login attempts.
                </p>
                <div className="flex flex-wrap gap-3">
                  <button
                    data-loading
                    className="bg-sky-600 hover:bg-sky-700 text-white px-6 py-3 rounded-xl font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500"
                  >
                    <i
                      className="fas fa-shield-alt mr-2"
                      aria-hidden="true"
                    ></i>
                    Enable 2FA
                  </button>
                  <button className="bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 px-4 py-3 rounded-xl font-medium transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-400">
                    Learn More
                  </button>
                </div>
              </div>

              <div
                className="bg-white rounded-2xl shadow-lg border border-slate-200/60 p-6 card-hover animate-slide-up"
                // style="animation-delay: 0.2s"
              >
                <div className="flex items-start mb-4">
                  <div
                    className="w-10 h-10 bg-sky-600 rounded-full flex items-center justify-center mr-4 text-white"
                    aria-hidden="true"
                  >
                    <i className="fas fa-key"></i>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-slate-900">
                      Password Management
                    </h3>
                    <div className="flex items-center mt-1">
                      <span className="text-sm text-slate-500">
                        Last changed: 15 days ago
                      </span>
                      <span className="ml-2 bg-yellow-100 text-yellow-800 px-2 py-1 rounded-full text-xs font-medium">
                        Due soon
                      </span>
                    </div>
                  </div>
                </div>
                <p className="text-slate-600 mb-6">
                  We recommend changing your password regularly for optimal
                  security. Use our password strength analyzer.
                </p>
                <button
                  data-loading
                  className="bg-orange-600 hover:bg-orange-700 text-white px-6 py-3 rounded-xl font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500"
                >
                  <i className="fas fa-sync-alt mr-2" aria-hidden="true"></i>
                  Change Password
                </button>
              </div>
            </div>

            <div className="space-y-6">
              <div
                className="bg-white rounded-2xl shadow-lg border border-slate-200/60 p-6 card-hover animate-slide-up"
                // style="animation-delay: 0.3s"
              >
                <div className="flex items-start mb-4">
                  <div
                    className="w-10 h-10 bg-purple-600 rounded-full flex items-center justify-center mr-4 text-white"
                    aria-hidden="true"
                  >
                    <i className="fas fa-history"></i>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-slate-900">
                      Recent Security Activity
                    </h3>
                    <p className="text-slate-600 mt-1">
                      Monitor your account access and changes
                    </p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-200">
                    <div className="flex items-center">
                      <div
                        className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center mr-3"
                        aria-hidden="true"
                      >
                        <i className="fas fa-laptop text-green-600 text-sm"></i>
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-slate-900">
                          Login from new device
                        </p>
                        <p className="text-xs text-slate-500">
                          Today at 14:23 • Chrome, Windows
                        </p>
                      </div>
                    </div>
                    <span className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-xs font-semibold">
                      <i className="fas fa-check mr-1" aria-hidden="true"></i>
                      Verified
                    </span>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-200">
                    <div className="flex items-center">
                      <div
                        className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center mr-3"
                        aria-hidden="true"
                      >
                        <i className="fas fa-key text-blue-600 text-sm"></i>
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-slate-900">
                          Password changed
                        </p>
                        <p className="text-xs text-slate-500">15 days ago</p>
                      </div>
                    </div>
                    <span className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-xs font-semibold">
                      <i
                        className="fas fa-check-circle mr-1"
                        aria-hidden="true"
                      ></i>
                      Completed
                    </span>
                  </div>
                </div>
              </div>

              <div
                className="relative overflow-hidden bg-white rounded-2xl shadow-lg border border-slate-200/60 p-6 card-hover animate-slide-up"
                // style="animation-delay: 0.4s"
              >
                <div className="flex items-start mb-4">
                  <div
                    className="w-10 h-10 bg-sky-600 rounded-full flex items-center justify-center mr-4 text-white"
                    aria-hidden="true"
                  >
                    <i className="fas fa-laptop"></i>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-slate-900">
                      Connected Devices
                    </h3>
                    <p className="text-slate-600 mt-1">3 active devices</p>
                  </div>
                  <img
                    src="https://images.unsplash.com/photo-1703589535872-93c3b0f96ba3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MDcxMzN8MHwxfHNlYXJjaHwxfHxkZXZpY2UlMjBzZWN1cml0eSUyMGxhcHRvcCUyMGxvY2slMjBtb2Rlcm4lMjB3b3Jrc3BhY2V8ZW58MHwwfHx8MTc1ODk2OTY5NXww&ixlib=rb-4.1.0&q=80&w=480"
                    alt="Secured laptop on a desk"
                    className="hidden md:block w-28 h-20 object-cover rounded-lg ml-4 ring-1 ring-slate-200/70"
                  />
                </div>
                <p className="text-slate-600 mb-6">
                  Manage devices that have access to your account. Review and
                  remove unfamiliar devices.
                </p>
                <div className="flex flex-wrap gap-3">
                  <button className="bg-slate-700 hover:bg-slate-800 text-white px-6 py-3 rounded-xl font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500">
                    <i className="fas fa-list mr-2" aria-hidden="true"></i>View
                    Devices
                  </button>
                  <button className="bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 px-4 py-3 rounded-xl font-medium transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-400">
                    <i className="fas fa-plus mr-2" aria-hidden="true"></i>Add
                    Device
                  </button>
                </div>
              </div>
            </div>
          </section>

          <section
            className="bg-white rounded-2xl shadow-lg border border-slate-200/60 p-8 card-hover animate-slide-up"
            // style="animation-delay: 0.5s"
            aria-labelledby="best-practices"
          >
            <div className="text-center mb-8">
              <h3
                id="best-practices"
                className="text-2xl font-bold text-slate-900 mb-2"
              >
                Security Best Practices
              </h3>
              <p className="text-slate-600">
                Follow these guidelines to keep your account secure
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div className="text-center p-4">
                <div
                  className="w-12 h-12 bg-sky-600 rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg text-white"
                  aria-hidden="true"
                >
                  <i className="fas fa-lock text-lg"></i>
                </div>
                <h4 className="font-semibold text-slate-900 mb-2">
                  Strong Passwords
                </h4>
                <p className="text-sm text-slate-500">
                  Use unique passwords across services
                </p>
              </div>

              <div className="text-center p-4">
                <div
                  className="w-12 h-12 bg-purple-600 rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg text-white"
                  aria-hidden="true"
                >
                  <i className="fas fa-fingerprint text-lg"></i>
                </div>
                <h4 className="font-semibold text-slate-900 mb-2">
                  Biometric Auth
                </h4>
                <p className="text-sm text-slate-500">
                  Enable fingerprint or face recognition
                </p>
              </div>

              <div className="text-center p-4">
                <div
                  className="w-12 h-12 bg-sky-600 rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg text-white"
                  aria-hidden="true"
                >
                  <i className="fas fa-chart-line text-lg"></i>
                </div>
                <h4 className="font-semibold text-slate-900 mb-2">
                  Activity Monitoring
                </h4>
                <p className="text-sm text-slate-500">
                  Regularly review login activity
                </p>
              </div>

              <div className="text-center p-4">
                <div
                  className="w-12 h-12 bg-purple-600 rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg text-white"
                  aria-hidden="true"
                >
                  <i className="fas fa-sync-alt text-lg"></i>
                </div>
                <h4 className="font-semibold text-slate-900 mb-2">
                  Regular Updates
                </h4>
                <p className="text-sm text-slate-500">
                  Keep app updated for latest patches
                </p>
              </div>
            </div>
          </section>

          <section
            className="relative mt-10 rounded-2xl shadow-lg border border-red-200 bg-linear-to-r from-red-50 to-orange-50 p-8 animate-slide-up overflow-hidden"
            // style="animation-delay: 0.6s"
            aria-labelledby="emergency-actions"
          >
            <img
              src="https://images.unsplash.com/photo-1592348283763-78f2ca1e1866?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MDcxMzN8MHwxfHNlYXJjaHwxfHxzZWN1cml0eSUyMHRlYW0lMjBzdXBwb3J0JTIwaGVscCUyMGNlbnRlcnxlbnwwfDB8fHwxNzU4OTY5Njk2fDA&ixlib=rb-4.1.0&q=80&w=800"
              alt=""
              aria-hidden="true"
              className="hidden md:block absolute right-0 top-0 h-full w-1/3 object-cover opacity-20"
            />
            <div className="flex items-center mb-6 relative">
              <div
                className="w-12 h-12 bg-linear-to-r from-red-500 to-orange-500 rounded-full flex items-center justify-center mr-4 text-white"
                aria-hidden="true"
              >
                <i className="fas fa-exclamation-triangle text-xl"></i>
              </div>
              <div>
                <h3
                  id="emergency-actions"
                  className="text-2xl font-bold text-slate-900"
                >
                  Emergency Actions
                </h3>
                <p className="text-slate-700">
                  Take immediate action if you suspect unauthorized access
                </p>
              </div>
            </div>
            <div className="grid md:grid-cols-2 gap-6">
              <button
                data-loading
                className="bg-red-600 hover:bg-red-700 text-white px-6 py-4 rounded-xl font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 flex items-center justify-center"
              >
                <i className="fas fa-ban mr-3 text-lg" aria-hidden="true"></i>
                Freeze Account
              </button>
              <button
                data-loading
                className="bg-orange-600 hover:bg-orange-700 text-white px-6 py-4 rounded-xl font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 flex items-center justify-center"
              >
                <i
                  className="fas fa-phone-alt mr-3 text-lg"
                  aria-hidden="true"
                ></i>
                Contact Support
              </button>
            </div>
          </section>

          <footer className="mt-12 text-center text-slate-500 text-sm">
            <p>
              © 2024 FinTech Security. All rights reserved. Your security is our
              priority.
            </p>
            <p className="mt-2">
              Need help?{" "}
              <a
                href="#"
                className="text-sky-600 hover:text-sky-700 font-medium"
              >
                Contact our security team
              </a>
            </p>
          </footer>
        </main>
      </body>
    </html>
  );
}
